In [2]:
from tensorflow.keras.preprocessing.text import one_hot


In [1]:
### sentences
sent=[  'the glass of milk',
     'the glass of juice',
     'the cup of tea',
    'I am a good boy',
     'I am a good developer',
     'understand the meaning of words',
     'your videos are good',]

In [5]:
## Define vocabulary size
voc_size = 10000
### One hot representation 
one_hot_repr = [one_hot(word, voc_size) for word in sent]
one_hot_repr

[[3112, 4154, 1374, 2402],
 [3112, 4154, 1374, 8232],
 [3112, 5184, 1374, 6030],
 [5971, 7564, 379, 5311, 8209],
 [5971, 7564, 379, 5311, 1699],
 [1159, 3112, 9535, 1374, 2628],
 [8627, 5208, 5734, 5311]]

In [7]:
from tensorflow.keras.layers import Embedding
from tensorflow.keras.preprocessing.sequence import pad_sequences
from tensorflow.keras.models import Sequential



In [8]:
import numpy as np

In [9]:
sent_lenth = 8 # max length of sentence
embedded_docs = pad_sequences(one_hot_repr, padding='pre', maxlen=sent_lenth)
print(embedded_docs)

[[   0    0    0    0 3112 4154 1374 2402]
 [   0    0    0    0 3112 4154 1374 8232]
 [   0    0    0    0 3112 5184 1374 6030]
 [   0    0    0 5971 7564  379 5311 8209]
 [   0    0    0 5971 7564  379 5311 1699]
 [   0    0    0 1159 3112 9535 1374 2628]
 [   0    0    0    0 8627 5208 5734 5311]]


In [10]:
# feature representation
dim = 10 
model = Sequential()
model.add(Embedding(voc_size,dim,input_length = sent_lenth))
model.compile('adam', 'mse')
print(model.summary())





Model: "sequential"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 embedding (Embedding)       (None, 8, 10)             100000    
                                                                 
Total params: 100000 (390.62 KB)
Trainable params: 100000 (390.62 KB)
Non-trainable params: 0 (0.00 Byte)
_________________________________________________________________
None


In [11]:
model.predict(embedded_docs )

1/1 [==============================] - 0s 70ms/step


array([[[ 0.00234212,  0.00141614,  0.02447618, -0.02052058,
         -0.01780105, -0.02635063, -0.02018234,  0.038032  ,
         -0.03880794, -0.01919557],
        [ 0.00234212,  0.00141614,  0.02447618, -0.02052058,
         -0.01780105, -0.02635063, -0.02018234,  0.038032  ,
         -0.03880794, -0.01919557],
        [ 0.00234212,  0.00141614,  0.02447618, -0.02052058,
         -0.01780105, -0.02635063, -0.02018234,  0.038032  ,
         -0.03880794, -0.01919557],
        [ 0.00234212,  0.00141614,  0.02447618, -0.02052058,
         -0.01780105, -0.02635063, -0.02018234,  0.038032  ,
         -0.03880794, -0.01919557],
        [ 0.04711192, -0.0398952 , -0.02157228, -0.02644807,
          0.02960468, -0.03359075,  0.0400177 ,  0.04608902,
          0.00831894, -0.03444522],
        [ 0.02741523,  0.0052309 , -0.00212811, -0.00118516,
         -0.01027988, -0.013011  , -0.00618281, -0.01082561,
          0.04551638, -0.01799881],
        [ 0.0053429 , -0.04759372,  0.02470723, -0.0